#
# This Dockerfile builds on
# src/multi_kobuki/Dockerfile
# of the workspaces repository (https://github.com/rerobots/workspaces.git)
#
# SCL <scott@rerobots.net>
# Copyright (C) 2020 rerobots, Inc.

FROM rerobots/workspaces-multi_kobuki:latest

RUN mkdir -p /root/sandbox_ws/src
COPY multi_kobuki_wander /root/sandbox_ws/src/multi_kobuki_wander
RUN bash -c 'source /opt/ros/melodic/setup.bash && cd /root/sandbox_ws/src && catkin_init_workspace && cd .. && catkin_make'

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install ros-melodic-rosbridge-suite

CMD ["/usr/sbin/sshd", "-D"]
